leftnav:
- identifier: 6b5d10a4-6968-fe06-c857-bb9820aebcbb
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 63c81b3f-5eaf-6bf8-a7a6-5754258ef6c2
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 9149f7b3-11d6-b30f-ba6e-a15e568bceb0
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: bf1d5614-3904-28fa-4114-ee613f799ea6
  name: Case Studies
  url: /pages/case-studies
  weight: 40
- identifier: fae32433-2a81-d0fd-9f84-7ae759233656
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 50
- identifier: ed13ee57-f245-c187-8b9a-a803d649c834
  name: Assignments
  url: /pages/assignments
  weight: 60
- identifier: ce4066fd-7bad-7aae-aa5c-15aca68b88a5
  name: Projects
  url: /pages/projects
  weight: 70
